//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaReta.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaReta.Common.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name already in use.
        /// </summary>
        public static string ACCOUNT_NAME_IN_USE {
            get {
                return ResourceManager.GetString("ACCOUNT_NAME_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        public static string ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than zero.
        /// </summary>
        public static string AMOUNT_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("AMOUNT_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name already exists.
        /// </summary>
        public static string CATEGORY_NAME_EXISTS {
            get {
                return ResourceManager.GetString("CATEGORY_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name must be between 3 and 50 characters.
        /// </summary>
        public static string CATEGORY_NAME_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CATEGORY_NAME_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category does not exist.
        /// </summary>
        public static string CATEGORY_NOT_EXISTS {
            get {
                return ResourceManager.GetString("CATEGORY_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found.
        /// </summary>
        public static string CATEGORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CATEGORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date out of range, must be between the beginning of the century and the next 5 years..
        /// </summary>
        public static string DATE_INVALID {
            get {
                return ResourceManager.GetString("DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description invalid.
        /// </summary>
        public static string DESCRIPTION_INVALID {
            get {
                return ResourceManager.GetString("DESCRIPTION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be between 3 and 120 characters.
        /// </summary>
        public static string DESCRIPTION_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("DESCRIPTION_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty or null.
        /// </summary>
        public static string EMAIL_EMPTY_OR_NULL {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY_OR_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already in use.
        /// </summary>
        public static string EMAIL_IN_USE {
            get {
                return ResourceManager.GetString("EMAIL_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid.
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty or null.
        /// </summary>
        public static string NAME_EMPTY_OR_NULL {
            get {
                return ResourceManager.GetString("NAME_EMPTY_OR_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is empty or null.
        /// </summary>
        public static string TITLE_EMPTY_OR_NULL {
            get {
                return ResourceManager.GetString("TITLE_EMPTY_OR_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction not found.
        /// </summary>
        public static string TRANSACTION_NOT_FOUND {
            get {
                return ResourceManager.GetString("TRANSACTION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is invalid.
        /// </summary>
        public static string TYPE_INVALID {
            get {
                return ResourceManager.GetString("TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
    }
}
